#!/usr/bin/env bash
#
# Run all dotfiles installers.
set -eo pipefail

install_pkg() {
  if test "$(which brew)"; then
    brew install "$@"
  fi
}

check_dependencies() {
  if test ! "$(which brew)"; then
    if test "$(uname)" = "Darwin"; then
      echo "  Installing Homebrew"
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
      echo "  Unsupported OS"
      exit 1
    fi
  fi
  if test ! "$(which git)"; then
    install_pkg git
  fi
  if test ! "$(which zsh)"; then
    install_pkg zsh
  fi
}

main() {
  if [ -d ~/.dotfiles ]; then
    echo "'~/.dotfiles' folder already exists, back it up and run 'install' again"
    exit 1
  fi
  check_dependencies
  git clone --recursive https://github.com/rosasej/dotfiles ~/.dotfiles
  cd ~/.dotfiles
  bash script/bootstrap
  echo "Thundercats Are GOOOOO! Restart your terminal session to complete install"
}
main